language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-head
  - rbx-3.20
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3.20

install:
  - gem install bundler -v "= 1.11.2"
  - bundle _1.11.2_ install

script: rake test
