language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-head
  - jruby-19mode
  - rbx-2
  - rbx-3
  - ruby-head
  - rbx-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: rbx-head

install: bundle install

script: rake test
